# Generated by Django 3.2.4 on 2021-07-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='job',
        ),
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/images/'),
        ),
    ]
